version: "4"

services:
  tf-serving:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    volumes:
      - ./new_models:/models/tomatoes_model
      - ./models.config:/models/models.config
    command: --model_config_file=/models/models.config --rest_api_port=8501
    restart: always
